# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56963600847545b6a9b64edc731b4bce1b528241c9c33e68e28bda9fadf60440643d459918fc1c98a06c1784aa0707e57d4bc1eb4c755e7411648260bd36f9da

test:
  secret_key_base: d60ad9e5686a05d93d935efad4335d5c8f3927d3a04c060c79f5bb1fcb02ec682c45f5ec26ed0cd74461c959fe9f14ac619d2c1e00a9bf262b46078fd63f6688

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
